### ISSUE TITLE
Reducing no of nodes does not work.

### ISSUE THREAD

**Issue by LutzLange** [liquidmetal-dev/cluster-api-provider-microvm#138]
**What happened:**
[A clear and concise description of what the bug is.]
I'm running capmvm 0.3.0 cluster on Equinix bare metal. Incerasing the no of nodes in my cluster works fine. Reducing the no of nodes does not. My nodes get the the NotReady stage and are not removed from the cluster list : 
![Screenshot from 2022-02-21 11-58-32](https://user-images.githubusercontent.com/2788194/154942548-a1b09462-10ff-46f0-a26f-f6ee333f85d2.png)

**What did you expect to happen:**
I did expect the nodes to vanish.

**Comment by richardcase** [comment]
I just tested this with the latest changes to flintlock/capmvm around instance_id & provider_id and this works. When we do the next releases this will hopefully no longer be an issue for you.
