### ISSUE TITLE
I can't deploy more than 1 control / master node

### ISSUE THREAD

**Issue by LutzLange** [liquidmetal-dev/cluster-api-provider-microvm#139]
**What happened:**
[A clear and concise description of what the bug is.]
If I request 3 control plane nodes, I get only one. I can't increase the control plane nodes later on as well.

**What did you expect to happen:**
Deploying a cluster with 3 control plane nodes should work.

**How to reproduce it:**
It is no https://demo.weavegitops.com .. I will give you access reach out on slack.

**Comment by richardcase** [comment]
I just tested this with the latest changes to flintlock/capmvm around instance_id & provider_id and this works. When we do the next releases this will hopefully no longer be an issue for you.
