### ISSUE TITLE
Add `FailureDomain` support to cluster controller

### ISSUE THREAD

**Issue by richardcase** [liquidmetal-dev/cluster-api-provider-microvm#14]
**Describe the solution you'd like:**
Implement the `FailureDomain` support in the clusters controller where a fault domain refers to a flintlock bare-metal host

**Why do you want this feature:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by richardcase** [comment]
Document the decision on what a fault domain is using an ADR as well

**Comment by Callisto13** [comment]
this has already gone into https://github.com/weaveworks/cluster-api-provider-microvm/pull/19 yes?

**Comment by richardcase** [comment]
Yes it has.....i added it as it helped the testing

**Comment by Callisto13** [comment]
cool, I will leave open to do the ADR
