### ISSUE TITLE
Change machine api to `additional kernel args`

### ISSUE THREAD

**Issue by richardcase** [liquidmetal-dev/cluster-api-provider-microvm#45]
**Describe the solution you'd like:**
Currently we expose [kernelCmdline](https://github.com/weaveworks/cluster-api-provider-microvm/blob/main/api/v1alpha1/types.go#L37) in the `MicrovmMachine` spec and set a default. 

For us to a boot a Firecracker microvm we should adopt an opinionated view on the kernel cmdline args and use ones that are recommended by FC or us and only allow the user to add to them.

**Why do you want this feature:**

**Anything else you would like to add:**

This is dependent on this: https://github.com/weaveworks/flintlock/issues/312

**Comment by yitsushi** [comment]
Blocked on: https://github.com/weaveworks/flintlock/issues/312
